# Generated by Django 4.0.5 on 2022-06-10 02:49

import addition.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[addition.validation.addition_exists])),
                ('content_type', models.CharField(choices=[('MO', 'Movie'), ('TV', 'TV Show')], default='MO', max_length=2)),
            ],
        ),
    ]
