name: CI

on:
  push:
    branches: [main]
  pull_request:
  release:
    types: [released]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_ISORT: true
          LINTER_RULES_PATH: /
          PYTHON_BLACK_CONFIG_FILE: pyproject.toml
          PYTHON_ISORT_CONFIG_FILE: pyproject.toml

  pytest:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: bakus
          POSTGRES_PASSWORD: bakus
          POSTGRES_DB: bakus-service
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: pip

    - name: Ensure latest pip
      run: |
        python -m pip install --upgrade pip

    - name: Install Python dependencies
      run: |
        pip install -r requirements-dev.txt

    - name: Test with pytest
      run: |
        pytest --cov=addition
        coverage lcov

    - name: Coveralls reporting
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
